#ifndef DYNAMIXEL_ARM__CONTROL_TABLE_HPP_
#define DYNAMIXEL_ARM__CONTROL_TABLE_HPP_


/****************Control Table Address for AX-12A*********************/
// EEPROM AREA
#define ADDR_MODEL_NUMBER 0
#define ADDR_FIRMWARE_VERSION 2
#define ADDR_ID 3
#define ADDR_BAUDRATE 4
#define ADDR_RETURN_DELAY_TIME 5
#define ADDR_CW_ANGLE_LIMIT 6
#define ADDR_CCW_ANGLE_LIMIT 8
#define ADDR_TEMP_LIMIT 11
#define ADDR_MIN_VOLT_LIMIT 12
#define ADDR_MAX_VOLT_LIMIT 13
#define ADDR_MAX_TORQUE 14
#define ADDR_STATUS_RETURN_LABEL 16
#define ADDR_ARLARM_LED 17
#define ADDR_SHUTDOWN 18

// RAM AREA
#define ADDR_TORQUE_ENABLE 24
#define ADDR_LED 25
#define ADDR_CW_COMPLIANCE_MARGIN 26
#define ADDR_CCW_COMPLIANCE_MARGIN 27
#define ADDR_CW_COMPLIANCE_SLOPE 28
#define ADDR_CCW_COMPLIANCE_SLOPE 29
#define ADDR_GOAL_POSITION 30
#define ADDR_MOVING_SPEED 32
#define ADDR_TORQUE_LIMIT 34
#define ADDR_PRESENT_POSITION 36
#define ADDR_PRESENT_SPEED 38
#define ADDR_PRESENT_LOAD 40
#define ADDR_PRESENT_VOLT 42
#define ADDR_PRESENT_TEMP 43
#define ADDR_REGISTARED 44
#define ADDR_MOVING 46
#define ADDR_LOCK 47
#define ADDR_PUNCH 48 

// Protocol version
#define PROTOCOL_VERSION 1.0f

// Default setting
#define BAUDRATE 1000000

#define WHEELMODE 0x3FF

#define DEVICE_NAME "/dev/ttyUSB0"

#endif  // DYNAMIXEL_ARM__CONTROL_TABLE_HPP_